services:
  pibus:
    image: '190n/pibus:latest'
    volumes:
      - 'pibus-html:/pibus'
      - './config.js:/app/config.js'
    environment:
      - 'TZ=America/Los_Angeles'
  cog:
    image: '190n/cog:latest'
    environment:
      - 'COG_URL=file:///pibus/index.html'
      - 'WLR_LIBINPUT_NO_DEVICES=1'
    volumes:
      - 'pibus-html:/pibus:ro'
      - '/dev/dri:/dev/dri'
    privileged: true
    depends_on:
      - 'pibus'
volumes:
  pibus-html:
